# .travis.yml for projeto

language: python

python:
  - "2.7"
  - "3.4"

script:
  coverage run testa.py

after_success:
  coveralls

#notifications:
#  email:
#    on_success: never
#    on_failure: never
